import * as _ from 'lodash'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

import Player, { IPlayer } from '../models/player'
import Serie, { ISerie } from '../models/serie'
import Team from '../models/team'

const createPlayers = async () => {
  const playersData = [
    // {
    //   fullName: "Antônio Marques",
    //   nickname: "Antônio",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Arthur Freire",
    //   nickname: "Arthur Freire",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Arthur Ribeiro",
    //   nickname: "Arthur Ribeiro",
    //   position: "Zagueiro",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Carlos Vitor",
    //   nickname: "Carlos",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Daniel Gondim",
    //   nickname: "Gondim",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Danilo Freitas",
    //   nickname: "Gordão",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Fábio Ferreira",
    //   nickname: "Bandana",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Felipe Diogo",
    //   nickname: "Pinhu",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Flávio Pimentel",
    //   nickname: "Flavinho",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Igor Dantas",
    //   nickname: "Iguinho",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Isaac Silva",
    //   nickname: "Isaac",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Jaime César",
    //   nickname: "Jaime",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Jefferson",
    //   nickname: "Jeff",
    //   position: "Goleiro",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Joeu Souza",
    //   nickname: "Joeu",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "João Victor",
    //   nickname: "Painha",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Leandro Brito",
    //   nickname: "Angolano",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Paulo Ouriques",
    //   nickname: "Paulinho",
    //   position: "Lateral",
    //   birthdate: "1987-02-20",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Pedro Raunny",
    //   nickname: "Pedrão",
    //   position: "Goleiro",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Pedro Saraiva",
    //   nickname: "Saraiva",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Francisco Raniere",
    //   nickname: "Raniere",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Raulino Maracajá",
    //   nickname: "Raulino",
    //   position: "Atacante",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Ricardo Baiano",
    //   nickname: "Baiano",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Thiago Fernando",
    //   nickname: "Thiago Fernando",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Thiago Freire",
    //   nickname: "Thiago Freire",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    // {
    //   fullName: "Silvio Leoterio",
    //   nickname: "Leoterio",
    //   position: "Meia",
    //   birthdate: "1989-05-19",
    //   picture: "https://i.stack.imgur.com/gMbrL.jpg",
    // },
    {
      fullName: 'Artur Farias',
      nickname: 'Artur Farias',
      position: 'Zagueiro',
      birthdate: '1989-05-19',
      picture: 'https://i.stack.imgur.com/gMbrL.jpg',
      active: false,
    },
    {
      fullName: 'Emerson Bruno',
      nickname: 'Bruno',
      position: 'Atacante',
      birthdate: '1989-05-19',
      picture: 'https://i.stack.imgur.com/gMbrL.jpg',
      active: false,
    },
    {
      fullName: 'Felipe Vieira Falcão',
      nickname: 'Vieira',
      position: 'Atacante',
      birthdate: '1989-05-19',
      picture: 'https://i.stack.imgur.com/gMbrL.jpg',
      active: false,
    },
    {
      fullName: 'Matheus Brasileiro Campos',
      nickname: 'Zé',
      position: 'Meia',
      birthdate: '1989-05-19',
      picture: 'https://i.stack.imgur.com/gMbrL.jpg',
      active: false,
    },
    {
      fullName: 'Renato Souto',
      nickname: 'Renato Souto',
      position: 'Meia',
      birthdate: '1989-05-19',
      picture: 'https://i.stack.imgur.com/gMbrL.jpg',
      active: false,
    },
    {
      fullName: 'Rodrigo Dantas',
      nickname: 'Rody',
      position: 'Meia',
      birthdate: '1989-05-19',
      picture: 'https://i.stack.imgur.com/gMbrL.jpg',
      active: false,
    },
  ]

  let players = []
  for (let playerData of playersData) {
    players.push(await new Player(playerData).save())
  }

  return players
}

const createSeries = async (players: Array<any>) => {
  const octoberTeams = [
    await new Team({
      color: 'Azul',
      players: players.slice(8, 16).map((p) => p._id),
    }).save(),
    await new Team({
      color: 'Laranja',
      players: players.slice(16).map((p) => p._id),
    }).save(),
    await new Team({
      color: 'Branco',
      players: players.slice(0, 8).map((p) => p._id),
    }).save(),
  ]
  const novemberTeams = [
    await new Team({
      color: 'Azul',
      players: players.slice(0, 8).map((p) => p._id),
    }).save(),
    await new Team({
      color: 'Laranja',
      players: players.slice(8, 16).map((p) => p._id),
    }).save(),
    await new Team({
      color: 'Branco',
      players: players.slice(16).map((p) => p._id),
    }).save(),
  ]

  const seriesData = [
    {
      month: 10,
      year: 2022,
      teams: octoberTeams,
      gameDays: [
        {
          date: new Date('2022-10-07'),
          matches: [
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 3,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: Math.floor(i / 10),
            assists: Math.floor((players.length - i - 1) / 10),
            score: 5,
          })),
        },
        {
          date: new Date('2022-01-14'),
          matches: [
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 3,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: Math.floor(i / 10),
            assists: Math.floor((players.length - i - 1) / 10),
            score: 6,
          })),
        },
        {
          date: new Date('2022-10-21'),
          matches: [
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 3,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: Math.floor(i / 10),
            assists: Math.floor((players.length - i - 1) / 10),
            score: 5,
          })),
        },
        {
          date: new Date('2022-10-28'),
          matches: [
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
              teamB: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
            },
            {
              teamA: {
                team: octoberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 2,
              },
              teamB: {
                team: octoberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: octoberTeams[2]._id,
                goals: 3,
              },
              teamB: {
                team: octoberTeams[1]._id,
                goals: 0,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: Math.floor(i / 10),
            assists: Math.floor((players.length - i - 1) / 10),
            score: 4,
          })),
        },
      ],
    },
    {
      month: 11,
      year: 2022,
      teams: novemberTeams,
      gameDays: [
        {
          date: new Date('2022-11-03'),
          matches: [
            {
              teamA: {
                team: novemberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: novemberTeams[1]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[0]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[1]._id,
                goals: 2,
              },
              teamB: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[0]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[1]._id,
                goals: 2,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: i,
            assists: players.length - i - 1,
            score: 5,
          })),
        },
        {
          date: new Date('2022-11-10'),
          matches: [
            {
              teamA: {
                team: novemberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: novemberTeams[1]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[0]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[1]._id,
                goals: 2,
              },
              teamB: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[0]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[1]._id,
                goals: 2,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: i,
            assists: players.length - i - 1,
            score: 5,
          })),
        },
        {
          date: new Date('2022-11-17'),
          matches: [
            {
              teamA: {
                team: novemberTeams[0]._id,
                goals: 0,
              },
              teamB: {
                team: novemberTeams[1]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[0]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[1]._id,
                goals: 2,
              },
              teamB: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[1]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[0]._id,
                goals: 0,
              },
            },
            {
              teamA: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[0]._id,
                goals: 1,
              },
            },
            {
              teamA: {
                team: novemberTeams[2]._id,
                goals: 1,
              },
              teamB: {
                team: novemberTeams[1]._id,
                goals: 2,
              },
            },
          ],
          playersStats: players.map((p, i) => ({
            player: p._id,
            goals: i,
            assists: players.length - i - 1,
            score: 5,
          })),
        },
      ],
    },
    {
      month: 2,
      year: 2023,
    },
  ]

  let series = []
  for (let serie of seriesData) {
    series.push(await new Serie(serie).save())
  }
  return series
}

const importSeries = async () => {
  const players = await Player.find({})
  // const playerByNickname = players.reduce((acc, player) => {
  //   acc[player.nickname] = player
  //   return acc
  // }, {})
  const playerByNickname = _.keyBy(players, 'nickname')
  const goals = [
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 1,
      Gordão: 4,
      Bruno: 3,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 1,
      Bruno: 2,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 1,
      Baiano: 2,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 1,
      Antônio: 2,
      Iguinho: 1,
      Gondim: 1,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 5,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 1,
      'Renato Souto': 1,
      Baiano: 1,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 1,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 3,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 2,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 4,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 4,
      'Renato Souto': 1,
      Baiano: 2,
      Rody: 1,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 1,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 0,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 3,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 1,
      Baiano: 1,
      Rody: 0,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 1,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 0,
      Gordão: 0,
      Bruno: 2,
      Bandana: 1,
      Vieira: 2,
      Flavinho: 2,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 1,
      Saraiva: 1,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 2,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 3,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 2,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 1,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 2,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 2,
      Bruno: 1,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 4,
      'Thiago Freire': 3,
      Jaime: 2,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 2,
      Baiano: 4,
      Rody: 0,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 2,
      Bruno: 1,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 2,
      'João Victor': 0,
      Angolano: 2,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 2,
      Raulino: 3,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 0,
      Joeu: 3,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 2,
      Bruno: 0,
      Bandana: 0,
      Vieira: 5,
      Flavinho: 4,
      'Thiago Freire': 3,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 2,
      Baiano: 3,
      Rody: 0,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 2,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 0,
      Saraiva: 2,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 1,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 4,
      Flavinho: 1,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 2,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 2,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 2,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 2,
      Baiano: 1,
      Rody: 0,
      Joeu: 1,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 0,
      Gordão: 1,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 2,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 1,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 1,
      Bruno: 1,
      Bandana: 1,
      Vieira: 2,
      Flavinho: 1,
      'Thiago Freire': 1,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 2,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 3,
      'Thiago Freire': 0,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 7,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 2,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 6,
      'Thiago Freire': 0,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 1,
      Saraiva: 1,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 2,
      Rody: 0,
      Joeu: 1,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 1,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 3,
      Bandana: 1,
      Vieira: 2,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 3,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 5,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 3,
      Joeu: 1,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 2,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 4,
      'Renato Souto': 0,
      Baiano: 1,
      Rody: 1,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 2,
      Iguinho: 1,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 2,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 2,
      Raulino: 0,
      'Renato Souto': 2,
      Baiano: 2,
      Rody: 1,
      Joeu: 0,
      Pinhu: 5,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 2,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 2,
      Bandana: 2,
      Vieira: 2,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 3,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 1,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 2,
      Angolano: 0,
      Zé: 0,
      Paulinho: 1,
      Saraiva: 1,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 1,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 4,
      'Thiago Freire': 0,
      Jaime: 3,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 2,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 2,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 2,
      Bruno: 3,
      Bandana: 1,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 5,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 2,
      'Renato Souto': 2,
      Baiano: 0,
      Rody: 0,
      Joeu: 1,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 1,
      Bruno: 2,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 1,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 1,
      Gordão: 2,
      Bruno: 0,
      Bandana: 1,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 1,
      'João Victor': 2,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 3,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 3,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 0,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 4,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 2,
      Joeu: 2,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 2,
      Bruno: 0,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 2,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 3,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 2,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 1,
      Bruno: 0,
      Bandana: 1,
      Vieira: 2,
      Flavinho: 0,
      'Thiago Freire': 4,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 2,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 2,
      Pinhu: 1,
    },
  ] as Array<{ [nickname: string]: number }>

  const assists = [
    {
      'Arthur Freire': 4,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 1,
      Gondim: 0,
      Gordão: 1,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 4,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 2,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 1,
      Gondim: 2,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 5,
      Baiano: 2,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 1,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 0,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 3,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 2,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 1,
      Bruno: 4,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 3,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 1,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 2,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 1,
      Bruno: 0,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 2,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 2,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 1,
      Saraiva: 2,
      Raulino: 0,
      'Renato Souto': 1,
      Baiano: 2,
      Rody: 2,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 2,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 2,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 2,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 4,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 1,
      Bruno: 2,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 3,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 2,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 1,
      Rody: 3,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 1,
      Bruno: 0,
      Bandana: 1,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 3,
      Baiano: 0,
      Rody: 3,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 3,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 1,
      'Thiago Freire': 0,
      Jaime: 2,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 2,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 1,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 3,
      Angolano: 0,
      Zé: 0,
      Paulinho: 2,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 2,
      Flavinho: 1,
      'Thiago Freire': 0,
      Jaime: 2,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 2,
      Pinhu: 3,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 1,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 1,
      Baiano: 1,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 2,
      Angolano: 0,
      Zé: 0,
      Paulinho: 1,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 3,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 1,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 0,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 1,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 1,
      Pinhu: 3,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 1,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 0,
      Bruno: 0,
      Bandana: 2,
      Vieira: 0,
      Flavinho: 3,
      'Thiago Freire': 2,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 4,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 1,
      Bruno: 1,
      Bandana: 1,
      Vieira: 2,
      Flavinho: 2,
      'Thiago Freire': 1,
      Jaime: 1,
      'João Victor': 2,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 4,
      Joeu: 1,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 2,
      'Arthur Ribeiro': 1,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 0,
      Bruno: 4,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 3,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 1,
      Rody: 0,
      Joeu: 2,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 3,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 2,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 2,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 5,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 2,
      Rody: 0,
      Joeu: 0,
      Pinhu: 3,
    },
    {
      'Arthur Freire': 1,
      'Arthur Ribeiro': 2,
      'Artur Farias': 1,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 0,
      Gordão: 1,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 1,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 1,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 1,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 1,
      Gondim: 1,
      Gordão: 1,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 6,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 1,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 3,
      'Thiago Freire': 0,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 2,
      Gondim: 0,
      Gordão: 1,
      Bruno: 1,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 1,
      'Thiago Freire': 2,
      Jaime: 1,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 1,
      Saraiva: 1,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 2,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 1,
      Gordão: 1,
      Bruno: 0,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 2,
      Gondim: 3,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 3,
      Jaime: 1,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 1,
      Joeu: 0,
      Pinhu: 1,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 2,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 1,
      Bruno: 0,
      Bandana: 0,
      Vieira: 0,
      Flavinho: 1,
      'Thiago Freire': 2,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 1,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 3,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 1,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 1,
      Vieira: 0,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 1,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 1,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 0,
      Rody: 0,
      Joeu: 1,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 0,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 0,
      Jaime: 0,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 1,
      Saraiva: 0,
      Raulino: 0,
      'Renato Souto': 0,
      Baiano: 2,
      Rody: 2,
      Joeu: 0,
      Pinhu: 0,
    },
    {
      'Arthur Freire': 0,
      'Arthur Ribeiro': 0,
      'Artur Farias': 0,
      Antônio: 0,
      Iguinho: 0,
      Gondim: 2,
      Gordão: 0,
      Bruno: 0,
      Bandana: 0,
      Vieira: 1,
      Flavinho: 0,
      'Thiago Freire': 1,
      Jaime: 1,
      'João Victor': 0,
      Angolano: 0,
      Zé: 0,
      Paulinho: 0,
      Saraiva: 0,
      Raulino: 1,
      'Renato Souto': 0,
      Baiano: 1,
      Rody: 2,
      Joeu: 0,
      Pinhu: 1,
    },
  ] as Array<{ [nickname: string]: number }>

  const series = [
    {
      year: 2022,
      month: 2,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-02-03') },
        { playersStats: [], matches: [], date: new Date('2022-02-10') },
        { playersStats: [], matches: [], date: new Date('2022-02-17') },
        { playersStats: [], matches: [], date: new Date('2022-02-24') },
      ],
    },
    {
      year: 2022,
      month: 3,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-03-03') },
        { playersStats: [], matches: [], date: new Date('2022-03-10') },
        { playersStats: [], matches: [], date: new Date('2022-03-17') },
        { playersStats: [], matches: [], date: new Date('2022-03-24') },
        { playersStats: [], matches: [], date: new Date('2022-03-31') },
      ],
    },
    {
      year: 2022,
      month: 4,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-04-07') },
        { playersStats: [], matches: [], date: new Date('2022-04-21') },
        { playersStats: [], matches: [], date: new Date('2022-04-28') },
      ],
    },
    {
      year: 2022,
      month: 5,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-05-05') },
        { playersStats: [], matches: [], date: new Date('2022-05-12') },
        { playersStats: [], matches: [], date: new Date('2022-05-19') },
        { playersStats: [], matches: [], date: new Date('2022-05-26') },
        { playersStats: [], matches: [], date: new Date('2022-06-03') },
        { playersStats: [], matches: [], date: new Date('2022-06-10') },
      ],
    },
    {
      year: 2022,
      month: 7,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-07-14') },
        { playersStats: [], matches: [], date: new Date('2022-07-21') },
        { playersStats: [], matches: [], date: new Date('2022-07-28') },
      ],
    },
    {
      year: 2022,
      month: 8,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-08-11') },
        { playersStats: [], matches: [], date: new Date('2022-08-18') },
        { playersStats: [], matches: [], date: new Date('2022-08-25') },
        { playersStats: [], matches: [], date: new Date('2022-09-01') },
      ],
    },
    {
      year: 2022,
      month: 9,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-09-08') },
        { playersStats: [], matches: [], date: new Date('2022-09-15') },
        { playersStats: [], matches: [], date: new Date('2022-09-22') },
        { playersStats: [], matches: [], date: new Date('2022-09-29') },
      ],
    },
    {
      year: 2022,
      month: 10,
      teams: [],
      gameDays: [
        { playersStats: [], matches: [], date: new Date('2022-10-20') },
        { playersStats: [], matches: [], date: new Date('2022-10-27') },
        { playersStats: [], matches: [], date: new Date('2022-11-03') },
        { playersStats: [], matches: [], date: new Date('2022-11-10') },
        { playersStats: [], matches: [], date: new Date('2022-11-17') },
      ],
    },
  ] as Array<ISerie>

  let gameDayIndex = 0
  for (const serie of series) {
    for (const gameDay of serie.gameDays) {
      const goalData = goals[gameDayIndex]
      const assistData = assists[gameDayIndex]
      gameDay.playersStats = Object.keys(goalData).map((nickname) => {
        const player = playerByNickname[nickname]

        if (nickname === 'Gordão') console.log(gameDayIndex, goalData[nickname])

        if (!player) throw `Player ${nickname} not found!`

        return {
          player: player._id,
          goals: goalData[nickname],
          assists: assistData[nickname],
        }
      })
      gameDayIndex++
    }
    await new Serie(serie).save()
  }
}

const main = async () => {
  // const players = await createPlayers();
  // console.log(`Created ${players.length} players`);
  // const series = await createSeries(players);
  // console.log(`Created ${series.length} series`);
  await importSeries()
}

main()
  .then(() => process.exit())
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
