import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "../config/theme";
import ApplicationBarComponent from "../components/ApplicationBarComponent";
import SideBarComponent from "../components/SideBarComponent";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <ApplicationBarComponent />
        <br />
        <div
          style={{
            width: "19%",
            position: "fixed",
            float: "right",
            right: 5,
            margin: 1,
            padding: 1,
          }}
        >
          <SideBarComponent currentTeamRanking={[]} />
        </div>
        <div
          style={{
            width: "79%",
            padding: 1,
            position: "fixed",
            float: "left",
            left: 5,
          }}
        ></div>
        {children}
      </ThemeProvider>
    </html>
  );
}

const latestTeamRanking = [
  {
    color: "Azul",
    score: 9,
    victories: 3,
    draws: 0,
    losses: 0,
  },
  {
    color: "Laranja",
    score: 4,
    victories: 1,
    draws: 1,
    losses: 2,
  },
  {
    color: "Branco",
    score: 1,
    victories: 0,
    draws: 1,
    losses: 3,
  },
];

const latestGameDayPlayerStats = [
  {
    playerId: "1",
    nickname: "Gordão",
    goals: 1,
    assists: 1,
    score: 1,
    victories: 1,
    draws: 1,
    losses: 1,
  },
  {
    playerId: "2",
    nickname: "Vieira",
    goals: 1,
    assists: 1,
    score: 1,
    victories: 1,
    draws: 1,
    losses: 1,
  },
  {
    playerId: "3",
    nickname: "Zé",
    goals: 1,
    assists: 1,
    score: 1,
    victories: 1,
    draws: 1,
    losses: 1,
  },
];
